### ISSUE TITLE
rfnoc_image_builder cannot convert gnuradio companion files

### ISSUE THREAD

**Issue by julixau** [EttusResearch/gr-ettus#54]
Hi, 

I am not sure, if this belongs here. Feel free to close this issue if this is the wrong place for it. 

the rfnoc_image_builder cannot convert gnuradio-companion graphs at the moment. 

```bash 
rfnoc_image_builder -r example/rfnoc_radio_ddc.grc -b /usr/share/gnuradio/grc/blocks
```
failes with 

```
[INF] Converting GNU Radio Companion file to image builder format
Traceback (most recent call last):
  File "/usr/bin/rfnoc_image_builder", line 212, in <module>
    sys.exit(main())
  File "/usr/bin/rfnoc_image_builder", line 190, in main
    config, source, device, target = image_config(args)
  File "/usr/bin/rfnoc_image_builder", line 120, in image_config
    config = image_builder.convert_to_image_config(config, args.grc_blocks)
  File "/usr/lib/python3.9/site-packages/uhd/imgbuilder/image_builder.py", line 498, in convert_to_image_config
    seps = {item["name"]: item for item in grc["blocks"] if item["parameters"]["type"] == 'sep'}
  File "/usr/lib/python3.9/site-packages/uhd/imgbuilder/image_builder.py", line 498, in <dictcomp>
    seps = {item["name"]: item for item in grc["blocks"] if item["parameters"]["type"] == 'sep'}
KeyError: 'type'
```

## Tool versions

- `uhd_config_info --version`: UHD 4.0.0.0-0-unknown
- gnuradio: GNU Radio Companion v3.8.0.0-953-g6de23f43
- gr-ettus: Commit 1038c4ce5135a2803b53554fc4971fe3de747d9a

**Comment by julixau** [comment]
OK, i think i have done the stupid. I now understand that there are builder blocks that need to be used here. 

I will investigate further and close this issue now.
